# Generated by Django 4.2.4 on 2023-09-06 07:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('BlogImages', models.FileField(upload_to='blogimg')),
                ('Category', models.CharField(max_length=250)),
                ('Summary', models.CharField(max_length=1000)),
                ('Content', models.CharField(max_length=1000)),
                ('IsDraft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.CharField(max_length=1000)),
                ('room', models.CharField(max_length=1000)),
                ('DrUser', models.CharField(max_length=1000)),
                ('PtUser', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DrUser', models.CharField(max_length=1000)),
                ('PtUser', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ProfilePicture', models.FileField(upload_to='profilepicture')),
                ('UserName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('UserType', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('ConfirmPassword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.BigIntegerField()),
                ('DoctorName', models.CharField(max_length=250)),
                ('Speciality', models.CharField(max_length=250)),
                ('AppointDate', models.DateField()),
                ('AppointStart', models.TimeField()),
                ('AppointEnd', models.CharField(max_length=250)),
                ('PatientName', models.CharField(max_length=250)),
                ('DoctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
    ]
